//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibreDiagnostics.Language.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibreDiagnostics.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibreDiagnostics.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string ButtonDonate {
            get {
                return ResourceManager.GetString("ButtonDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Github.
        /// </summary>
        public static string ButtonGithub {
            get {
                return ResourceManager.GetString("ButtonGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string ButtonRestart {
            get {
                return ResourceManager.GetString("ButtonRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Clock.
        /// </summary>
        public static string CPUClock {
            get {
                return ResourceManager.GetString("CPUClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string CPUClockLabel {
            get {
                return ResourceManager.GetString("CPUClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Load.
        /// </summary>
        public static string CPUCoreLoad {
            get {
                return ResourceManager.GetString("CPUCoreLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.
        /// </summary>
        public static string CPUCoreLoadLabel {
            get {
                return ResourceManager.GetString("CPUCoreLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Fan.
        /// </summary>
        public static string CPUFan {
            get {
                return ResourceManager.GetString("CPUFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string CPUFanLabel {
            get {
                return ResourceManager.GetString("CPUFanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Load.
        /// </summary>
        public static string CPULoad {
            get {
                return ResourceManager.GetString("CPULoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string CPULoadLabel {
            get {
                return ResourceManager.GetString("CPULoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Temperature.
        /// </summary>
        public static string CPUTemp {
            get {
                return ResourceManager.GetString("CPUTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string CPUTempLabel {
            get {
                return ResourceManager.GetString("CPUTempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Voltage.
        /// </summary>
        public static string CPUVoltage {
            get {
                return ResourceManager.GetString("CPUVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string CPUVoltageLabel {
            get {
                return ResourceManager.GetString("CPUVoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Space.
        /// </summary>
        public static string DriveFree {
            get {
                return ResourceManager.GetString("DriveFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string DriveFreeLabel {
            get {
                return ResourceManager.GetString("DriveFreeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string DriveLoad {
            get {
                return ResourceManager.GetString("DriveLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Bar.
        /// </summary>
        public static string DriveLoadBar {
            get {
                return ResourceManager.GetString("DriveLoadBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string DriveLoadBarLabel {
            get {
                return ResourceManager.GetString("DriveLoadBarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string DriveLoadLabel {
            get {
                return ResourceManager.GetString("DriveLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Rate.
        /// </summary>
        public static string DriveRead {
            get {
                return ResourceManager.GetString("DriveRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string DriveReadLabel {
            get {
                return ResourceManager.GetString("DriveReadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        public static string Drives {
            get {
                return ResourceManager.GetString("Drives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string DriveTemperature {
            get {
                return ResourceManager.GetString("DriveTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string DriveTemperatureLabel {
            get {
                return ResourceManager.GetString("DriveTemperatureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used Space.
        /// </summary>
        public static string DriveUsed {
            get {
                return ResourceManager.GetString("DriveUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string DriveUsedLabel {
            get {
                return ResourceManager.GetString("DriveUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Rate.
        /// </summary>
        public static string DriveWrite {
            get {
                return ResourceManager.GetString("DriveWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        public static string DriveWriteLabel {
            get {
                return ResourceManager.GetString("DriveWriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fans.
        /// </summary>
        public static string Fan {
            get {
                return ResourceManager.GetString("Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan Speed.
        /// </summary>
        public static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string FanSpeedLabel {
            get {
                return ResourceManager.GetString("FanSpeedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU.
        /// </summary>
        public static string GPU {
            get {
                return ResourceManager.GetString("GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Clock.
        /// </summary>
        public static string GPUCoreClock {
            get {
                return ResourceManager.GetString("GPUCoreClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string GPUCoreClockLabel {
            get {
                return ResourceManager.GetString("GPUCoreClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core Load.
        /// </summary>
        public static string GPUCoreLoad {
            get {
                return ResourceManager.GetString("GPUCoreLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string GPUCoreLoadLabel {
            get {
                return ResourceManager.GetString("GPUCoreLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Fan.
        /// </summary>
        public static string GPUFan {
            get {
                return ResourceManager.GetString("GPUFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string GPUFanLabel {
            get {
                return ResourceManager.GetString("GPUFanLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string GPUTemp {
            get {
                return ResourceManager.GetString("GPUTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string GPUTempLabel {
            get {
                return ResourceManager.GetString("GPUTempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Voltage.
        /// </summary>
        public static string GPUVoltage {
            get {
                return ResourceManager.GetString("GPUVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string GPUVoltageLabel {
            get {
                return ResourceManager.GetString("GPUVoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM Clock.
        /// </summary>
        public static string GPUVRAMClock {
            get {
                return ResourceManager.GetString("GPUVRAMClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM.
        /// </summary>
        public static string GPUVRAMClockLabel {
            get {
                return ResourceManager.GetString("GPUVRAMClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM Load.
        /// </summary>
        public static string GPUVRAMLoad {
            get {
                return ResourceManager.GetString("GPUVRAMLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM.
        /// </summary>
        public static string GPUVRAMLoadLabel {
            get {
                return ResourceManager.GetString("GPUVRAMLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will restart to change language..
        /// </summary>
        public static string LanguageChangedText {
            get {
                return ResourceManager.GetString("LanguageChangedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language was changed.
        /// </summary>
        public static string LanguageChangedTitle {
            get {
                return ResourceManager.GetString("LanguageChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External IP Address.
        /// </summary>
        public static string NetworkExtIP {
            get {
                return ResourceManager.GetString("NetworkExtIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext.
        /// </summary>
        public static string NetworkExtIPLabel {
            get {
                return ResourceManager.GetString("NetworkExtIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth in.
        /// </summary>
        public static string NetworkIn {
            get {
                return ResourceManager.GetString("NetworkIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string NetworkInLabel {
            get {
                return ResourceManager.GetString("NetworkInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        public static string NetworkIP {
            get {
                return ResourceManager.GetString("NetworkIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string NetworkIPLabel {
            get {
                return ResourceManager.GetString("NetworkIPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth out.
        /// </summary>
        public static string NetworkOut {
            get {
                return ResourceManager.GetString("NetworkOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string NetworkOutLabel {
            get {
                return ResourceManager.GetString("NetworkOutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value.
        /// </summary>
        public static string NoSensorValue {
            get {
                return ResourceManager.GetString("NoSensorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM Clock.
        /// </summary>
        public static string RAMClock {
            get {
                return ResourceManager.GetString("RAMClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string RAMClockLabel {
            get {
                return ResourceManager.GetString("RAMClockLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string RAMFree {
            get {
                return ResourceManager.GetString("RAMFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free.
        /// </summary>
        public static string RAMFreeLabel {
            get {
                return ResourceManager.GetString("RAMFreeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string RAMLoad {
            get {
                return ResourceManager.GetString("RAMLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string RAMLoadLabel {
            get {
                return ResourceManager.GetString("RAMLoadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string RAMTemp {
            get {
                return ResourceManager.GetString("RAMTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp.
        /// </summary>
        public static string RAMTempLabel {
            get {
                return ResourceManager.GetString("RAMTempLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string RAMUsed {
            get {
                return ResourceManager.GetString("RAMUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string RAMUsedLabel {
            get {
                return ResourceManager.GetString("RAMUsedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM Voltage.
        /// </summary>
        public static string RAMVoltage {
            get {
                return ResourceManager.GetString("RAMVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string RAMVoltageLabel {
            get {
                return ResourceManager.GetString("RAMVoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string SettingsAdvancedTab {
            get {
                return ResourceManager.GetString("SettingsAdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert font color.
        /// </summary>
        public static string SettingsAlertFontColor {
            get {
                return ResourceManager.GetString("SettingsAlertFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color of item with an active alert..
        /// </summary>
        public static string SettingsAlertFontColorTooltip {
            get {
                return ResourceManager.GetString("SettingsAlertFontColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all core clocks.
        /// </summary>
        public static string SettingsAllCoreClocks {
            get {
                return ResourceManager.GetString("SettingsAllCoreClocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the clock speeds of all cores instead of only the first one..
        /// </summary>
        public static string SettingsAllCoreClocksTooltip {
            get {
                return ResourceManager.GetString("SettingsAllCoreClocksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on top.
        /// </summary>
        public static string SettingsAlwaysOnTop {
            get {
                return ResourceManager.GetString("SettingsAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the application to always be on top of other windows..
        /// </summary>
        public static string SettingsAlwaysOnTopTooltip {
            get {
                return ResourceManager.GetString("SettingsAlwaysOnTopTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App width.
        /// </summary>
        public static string SettingsAppWidth {
            get {
                return ResourceManager.GetString("SettingsAppWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of the application..
        /// </summary>
        public static string SettingsAppWidthTooltip {
            get {
                return ResourceManager.GetString("SettingsAppWidthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto background color.
        /// </summary>
        public static string SettingsAutoBackground {
            get {
                return ResourceManager.GetString("SettingsAutoBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the background color to your systems color settings..
        /// </summary>
        public static string SettingsAutoBackgroundTooltip {
            get {
                return ResourceManager.GetString("SettingsAutoBackgroundTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto font color.
        /// </summary>
        public static string SettingsAutoFontColor {
            get {
                return ResourceManager.GetString("SettingsAutoFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the font color to your systems color settings..
        /// </summary>
        public static string SettingsAutoFontColorTooltip {
            get {
                return ResourceManager.GetString("SettingsAutoFontColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update.
        /// </summary>
        public static string SettingsAutoUpdate {
            get {
                return ResourceManager.GetString("SettingsAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks for updates when starting the application and updates automatically..
        /// </summary>
        public static string SettingsAutoUpdateTooltip {
            get {
                return ResourceManager.GetString("SettingsAutoUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string SettingsBackgroundColor {
            get {
                return ResourceManager.GetString("SettingsBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the background..
        /// </summary>
        public static string SettingsBackgroundColorTooltip {
            get {
                return ResourceManager.GetString("SettingsBackgroundColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background opacity.
        /// </summary>
        public static string SettingsBackgroundOpacity {
            get {
                return ResourceManager.GetString("SettingsBackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity of the background..
        /// </summary>
        public static string SettingsBackgroundOpacityTooltip {
            get {
                return ResourceManager.GetString("SettingsBackgroundOpacityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth in alert.
        /// </summary>
        public static string SettingsBandwidthInAlert {
            get {
                return ResourceManager.GetString("SettingsBandwidthInAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MBps threshold at which bandwidth received alerts occur. Use 0 to disable..
        /// </summary>
        public static string SettingsBandwidthInAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsBandwidthInAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandwidth out alert.
        /// </summary>
        public static string SettingsBandwidthOutAlert {
            get {
                return ResourceManager.GetString("SettingsBandwidthOutAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MBps threshold at which bandwidth sent alerts occur. Use 0 to disable..
        /// </summary>
        public static string SettingsBandwidthOutAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsBandwidthOutAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click through.
        /// </summary>
        public static string SettingsClickThrough {
            get {
                return ResourceManager.GetString("SettingsClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any mouse events will pass through the window. This will prevent any interaction with the application..
        /// </summary>
        public static string SettingsClickThroughTooltip {
            get {
                return ResourceManager.GetString("SettingsClickThroughTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show core loads.
        /// </summary>
        public static string SettingsCoreLoads {
            get {
                return ResourceManager.GetString("SettingsCoreLoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the percentage load of all cores..
        /// </summary>
        public static string SettingsCoreLoadsTooltip {
            get {
                return ResourceManager.GetString("SettingsCoreLoadsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize.
        /// </summary>
        public static string SettingsCustomizeTab {
            get {
                return ResourceManager.GetString("SettingsCustomizeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string SettingsDock {
            get {
                return ResourceManager.GetString("SettingsDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string SettingsDockLeft {
            get {
                return ResourceManager.GetString("SettingsDockLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string SettingsDockRight {
            get {
                return ResourceManager.GetString("SettingsDockRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines where the application will dock..
        /// </summary>
        public static string SettingsDockTooltip {
            get {
                return ResourceManager.GetString("SettingsDockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color.
        /// </summary>
        public static string SettingsFontColor {
            get {
                return ResourceManager.GetString("SettingsFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of text and icons..
        /// </summary>
        public static string SettingsFontColorTooltip {
            get {
                return ResourceManager.GetString("SettingsFontColorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font family.
        /// </summary>
        public static string SettingsFontFamily {
            get {
                return ResourceManager.GetString("SettingsFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font family of texts..
        /// </summary>
        public static string SettingsFontFamilyTooltip {
            get {
                return ResourceManager.GetString("SettingsFontFamilyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string SettingsFontSize {
            get {
                return ResourceManager.GetString("SettingsFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of text and icons..
        /// </summary>
        public static string SettingsFontSizeTooltip {
            get {
                return ResourceManager.GetString("SettingsFontSizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SettingsGeneralTab {
            get {
                return ResourceManager.GetString("SettingsGeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string SettingsHardwareEnabled {
            get {
                return ResourceManager.GetString("SettingsHardwareEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables this hardware..
        /// </summary>
        public static string SettingsHardwareEnabledTooltip {
            get {
                return ResourceManager.GetString("SettingsHardwareEnabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware.
        /// </summary>
        public static string SettingsHardwareName {
            get {
                return ResourceManager.GetString("SettingsHardwareName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the name of this hardware..
        /// </summary>
        public static string SettingsHardwareNameTooltip {
            get {
                return ResourceManager.GetString("SettingsHardwareNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal offset.
        /// </summary>
        public static string SettingsHorizontalOffset {
            get {
                return ResourceManager.GetString("SettingsHorizontalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal offset of the application..
        /// </summary>
        public static string SettingsHorizontalOffsetTooltip {
            get {
                return ResourceManager.GetString("SettingsHorizontalOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appbar.
        /// </summary>
        public static string SettingsIsAppBar {
            get {
                return ResourceManager.GetString("SettingsIsAppBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the window as appbar and reserves spaces in the work area accordingly..
        /// </summary>
        public static string SettingsIsAppBarTooltip {
            get {
                return ResourceManager.GetString("SettingsIsAppBarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is in Alt + Tab.
        /// </summary>
        public static string SettingsIsInAltTab {
            get {
                return ResourceManager.GetString("SettingsIsInAltTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides the application in Alt + Tab..
        /// </summary>
        public static string SettingsIsInAltTabTooltip {
            get {
                return ResourceManager.GetString("SettingsIsInAltTabTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string SettingsLanguageDefault {
            get {
                return ResourceManager.GetString("SettingsLanguageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language of the application..
        /// </summary>
        public static string SettingsLanguageTooltip {
            get {
                return ResourceManager.GetString("SettingsLanguageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics:.
        /// </summary>
        public static string SettingsMetrics {
            get {
                return ResourceManager.GetString("SettingsMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable specific metrics..
        /// </summary>
        public static string SettingsMetricsTooltip {
            get {
                return ResourceManager.GetString("SettingsMetricsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables this monitor..
        /// </summary>
        public static string SettingsMonitorEnabledTooltip {
            get {
                return ResourceManager.GetString("SettingsMonitorEnabledTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click a row to edit its settings..
        /// </summary>
        public static string SettingsMonitorsDragDropTitle1 {
            get {
                return ResourceManager.GetString("SettingsMonitorsDragDropTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a row to change its order..
        /// </summary>
        public static string SettingsMonitorsDragDropTitle2 {
            get {
                return ResourceManager.GetString("SettingsMonitorsDragDropTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string SettingsMonitorsEnabled {
            get {
                return ResourceManager.GetString("SettingsMonitorsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string SettingsMonitorsMonitor {
            get {
                return ResourceManager.GetString("SettingsMonitorsMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitors.
        /// </summary>
        public static string SettingsMonitorsTab {
            get {
                return ResourceManager.GetString("SettingsMonitorsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round all decimals.
        /// </summary>
        public static string SettingsRoundAllDecimals {
            get {
                return ResourceManager.GetString("SettingsRoundAllDecimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round all decimal values to the nearest integer..
        /// </summary>
        public static string SettingsRoundAllDecimalsTooltip {
            get {
                return ResourceManager.GetString("SettingsRoundAllDecimalsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup.
        /// </summary>
        public static string SettingsRunAtStartup {
            get {
                return ResourceManager.GetString("SettingsRunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the application with the system - after you initially logged in..
        /// </summary>
        public static string SettingsRunAtStartupTooltip {
            get {
                return ResourceManager.GetString("SettingsRunAtStartupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string SettingsScreen {
            get {
                return ResourceManager.GetString("SettingsScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines which screen the application will be on..
        /// </summary>
        public static string SettingsScreenTooltip {
            get {
                return ResourceManager.GetString("SettingsScreenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hardware names.
        /// </summary>
        public static string SettingsShowHardwareNames {
            get {
                return ResourceManager.GetString("SettingsShowHardwareNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows hardware names..
        /// </summary>
        public static string SettingsShowHardwareNamesTooltip {
            get {
                return ResourceManager.GetString("SettingsShowHardwareNamesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show inactive connections.
        /// </summary>
        public static string SettingsShowInactiveConnections {
            get {
                return ResourceManager.GetString("SettingsShowInactiveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows network connections without transferred data..
        /// </summary>
        public static string SettingsShowInactiveConnectionsTooltip {
            get {
                return ResourceManager.GetString("SettingsShowInactiveConnectionsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show inactive fans.
        /// </summary>
        public static string SettingsShowInactiveFans {
            get {
                return ResourceManager.GetString("SettingsShowInactiveFans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show fans with a RPM of zero. This re-checks a fans RPM in each update cycle..
        /// </summary>
        public static string SettingsShowInactiveFansTooltip {
            get {
                return ResourceManager.GetString("SettingsShowInactiveFansTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show menu bar.
        /// </summary>
        public static string SettingsShowMenuBar {
            get {
                return ResourceManager.GetString("SettingsShowMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the menu bar at top of the application..
        /// </summary>
        public static string SettingsShowMenuBarTooltip {
            get {
                return ResourceManager.GetString("SettingsShowMenuBarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tray icon.
        /// </summary>
        public static string SettingsShowTrayIcon {
            get {
                return ResourceManager.GetString("SettingsShowTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the tray icon in the taskbar..
        /// </summary>
        public static string SettingsShowTrayIconTooltip {
            get {
                return ResourceManager.GetString("SettingsShowTrayIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature alert.
        /// </summary>
        public static string SettingsTemperatureAlert {
            get {
                return ResourceManager.GetString("SettingsTemperatureAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The temperature threshold at which alerts occur. Use 0 to disable..
        /// </summary>
        public static string SettingsTemperatureAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsTemperatureAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text align.
        /// </summary>
        public static string SettingsTextAlignment {
            get {
                return ResourceManager.GetString("SettingsTextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string SettingsTextAlignmentLeft {
            get {
                return ResourceManager.GetString("SettingsTextAlignmentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string SettingsTextAlignmentRight {
            get {
                return ResourceManager.GetString("SettingsTextAlignmentRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment of text..
        /// </summary>
        public static string SettingsTextAlignmentTooltip {
            get {
                return ResourceManager.GetString("SettingsTextAlignmentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update throttle.
        /// </summary>
        public static string SettingsThrottleInterval {
            get {
                return ResourceManager.GetString("SettingsThrottleInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttles sensor updates for storage devices by entered number in milliseconds. Use 0 to disable the update throttle..
        /// </summary>
        public static string SettingsThrottleIntervalTooltip {
            get {
                return ResourceManager.GetString("SettingsThrottleIntervalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LibreDiagnostics settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Interval.
        /// </summary>
        public static string SettingsUpdateInterval {
            get {
                return ResourceManager.GetString("SettingsUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time between sensor updates in milliseconds..
        /// </summary>
        public static string SettingsUpdateIntervalTooltip {
            get {
                return ResourceManager.GetString("SettingsUpdateIntervalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used space alert.
        /// </summary>
        public static string SettingsUsedSpaceAlert {
            get {
                return ResourceManager.GetString("SettingsUsedSpaceAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage threshold at which used space alerts occur. Use 0 to disable..
        /// </summary>
        public static string SettingsUsedSpaceAlertTooltip {
            get {
                return ResourceManager.GetString("SettingsUsedSpaceAlertTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fahrenheit.
        /// </summary>
        public static string SettingsUseFahrenheit {
            get {
                return ResourceManager.GetString("SettingsUseFahrenheit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatures for sensors and alerts will be in Fahrenheit instead of Celsius..
        /// </summary>
        public static string SettingsUseFahrenheitTooltip {
            get {
                return ResourceManager.GetString("SettingsUseFahrenheitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical offset.
        /// </summary>
        public static string SettingsVerticalOffset {
            get {
                return ResourceManager.GetString("SettingsVerticalOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical offset of the application..
        /// </summary>
        public static string SettingsVerticalOffsetTooltip {
            get {
                return ResourceManager.GetString("SettingsVerticalOffsetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.M.A.R.T. Attributes.
        /// </summary>
        public static string StorageAttributeHeader {
            get {
                return ResourceManager.GetString("StorageAttributeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Monitoring, Analysis and Reporting Technology (SMART / S.M.A.R.T.).
        /// </summary>
        public static string StorageAttributeHeaderTooltip {
            get {
                return ResourceManager.GetString("StorageAttributeHeaderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string StorageAttributeID {
            get {
                return ResourceManager.GetString("StorageAttributeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StorageAttributeName {
            get {
                return ResourceManager.GetString("StorageAttributeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string StorageAttributeValue {
            get {
                return ResourceManager.GetString("StorageAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value (Hex).
        /// </summary>
        public static string StorageAttributeValueHex {
            get {
                return ResourceManager.GetString("StorageAttributeValueHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string StorageHealth {
            get {
                return ResourceManager.GetString("StorageHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health of storage device..
        /// </summary>
        public static string StorageHealthTooltip {
            get {
                return ResourceManager.GetString("StorageHealthTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StorageName {
            get {
                return ResourceManager.GetString("StorageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of storage device..
        /// </summary>
        public static string StorageNameTooltip {
            get {
                return ResourceManager.GetString("StorageNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage details.
        /// </summary>
        public static string StorageTitle {
            get {
                return ResourceManager.GetString("StorageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available for download. Would you like to proceed with the update ?.
        /// </summary>
        public static string UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available.
        /// </summary>
        public static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
    }
}
